# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  zephyr_nginx:
    image: nginx:1.21.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  zephyr_tomcat_1:
    image: tomcat:8.5.76
    volumes:
      - ../build/libs/shopping_cart_demo.war:/usr/local/tomcat/webapps/shopping_cart_demo.war
    depends_on:
      - zephyr_db
    ports:
      - 8081:8080
  zephyr_tomcat_2:
    image: tomcat:8.5.76
    volumes:
      - ../build/libs/shopping_cart_demo.war:/usr/local/tomcat/webapps/shopping_cart_demo.war
    depends_on:
      - zephyr_db
    ports:
      - 8082:8080
  zephyr_tomcat_3:
    image: tomcat:8.5.76
    volumes:
      - ../build/libs/shopping_cart_demo.war:/usr/local/tomcat/webapps/shopping_cart_demo.war
    depends_on:
      - zephyr_db
    ports:
      - 8083:8080
  zephyr_tomcat_4:
    image: tomcat:8.5.76
    volumes:
      - ../build/libs/shopping_cart_demo.war:/usr/local/tomcat/webapps/shopping_cart_demo.war
    depends_on:
      - zephyr_db
    ports:
      - 8084:8080
  zephyr_tomcat_5:
    image: tomcat:8.5.76
    volumes:
      - ../build/libs/shopping_cart_demo.war:/usr/local/tomcat/webapps/shopping_cart_demo.war
    depends_on:
      - zephyr_db
    ports:
      - 8085:8080
  zephyr_db:
    image: postgres:latest # 12.4 version
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - zephyr_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "zephyr_admin"
      POSTGRES_DB: "zephyr_db"
      POSTGRES_PASSWORD: "zephyr_pwd"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"

volumes:
  zephyr_dbdata: