DROP TABLE IF EXISTS ORDER_LIST;
CREATE TABLE ORDER_LIST (
    ID SERIAL PRIMARY KEY,
    PRODUCT_NAME VARCHAR(20),
    SIZE VARCHAR(2),
    QUANTITY INTEGER,
    PRICE INTEGER,
    SUB_TOTAL INTEGER,
    STATUS INTEGER,
    ORDER_ID VARCHAR (20)
);